# Generated by Django 3.1.2 on 2020-10-25 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20201025_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciepent', models.CharField(max_length=255)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='Dashboard.class')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(related_name='classes', to='Dashboard.People'),
        ),
        migrations.AddField(
            model_name='class',
            name='teaching_assistant',
            field=models.ManyToManyField(related_name='assist_classes', to='Dashboard.People'),
        ),
    ]
