# Generated by Django 3.1.4 on 2020-12-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reciepent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
