# Generated by Django 3.1.4 on 2020-12-05 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20201205_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.ManyToManyField(related_name='recieved_notif', to=settings.AUTH_USER_MODEL),
        ),
    ]
