# Generated by Django 3.1.4 on 2020-12-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reciepent',
            field=models.CharField(default='student', max_length=255),
            preserve_default=False,
        ),
    ]
