# Generated by Django 3.1.4 on 2020-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_notification_reciepent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(default='High', max_length=255),
            preserve_default=False,
        ),
    ]
