# Generated by Django 3.1.4 on 2020-12-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_notification_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',)},
        ),
    ]
